spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

DEMO_S3_ACCESS_KEY_ID=
DEMO_S3_SECRET_ACCESS_KEY=
DEMO_S3_REGION=
DEMO_S3_BUCKET=

DEMO_SQS_QUEUE_URL=
DEMO_SQS_QUEUE_NAME=
DEMO_SQS_AUTO_CREATE=true
sqs.poller.enabled=false
sqs.poller.fixed-delay-ms=10000
sqs.poller.initial-delay-ms=3000
sqs.poller.max-number=5
sqs.poller.wait-seconds=0
sqs.poller.auto-delete=false
upload.status.poller.enabled=true
upload.status.poller.fixed-delay-ms=15000
upload.status.poller.initial-delay-ms=5000
upload.status.poller.max-retry=6
spring.data.redis.host=127.0.0.1
spring.data.redis.port=6379
spring.data.redis.timeout=5s
upload.task.cache.ttl-seconds=3600
